name: Tests

on:
  push:
    branches:
      - main

jobs:
  bats:
    name: bats-core test suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bats-core
        run: |
          sudo apt-get update -q
          sudo apt-get install -y bats

      - name: Run tests
        run: bats tests/
